apiVersion: v1
kind: Service
metadata:
  labels:
    app: tea
  name: test-svc-tea
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tea # You must specify the value of the matchLabels parameter in the YAML file used to create the Deployment.
  type: LoadBalancer
